### ISSUE TITLE
"State of the Field" in paper

### ISSUE THREAD

**Issue by lrasmus** [PopMedNet-Team/popmednet#39]
As part of https://github.com/openjournals/joss-reviews/issues/4062 JOSS guidelines ask for "_State of the field: Do the authors describe how this software compares to other commonly-used packages?_"

I do not see comparison to other used packages and software (i2b2/SHRINE, OMOP/OHDSI stack, Leaf, etc.) Could you please add this to the paper?

**Comment by ddeehere** [comment]
@lrasmus Just want to let you know that I am still working on this. I do have some experience with I2B2 and Shrine, but it may be dated. So I need to brush up on their recent development.

**Comment by ddeehere** [comment]
@lrasmus I added a section "Comparison to i2b2 and SHRINE" for "State of the Field" in paper.md.
